table 'Date Range'
	lineageTag: ba908f52-128e-4385-b0f7-05a9f872ab68

	column '1, 3 or 12 months'
		dataType: int64
		formatString: 0
		lineageTag: a150a2d9-3945-41b4-ab32-931c1c9dfd28
		summarizeBy: sum
		sourceColumn: 1, 3 or 12 months

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: aab802b1-e2a2-437e-8947-fc5428a5f33a
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	partition 'Date Range' = m
		mode: import
		queryGroup: 'New Tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W0jVU0lHySSwuUfDNzyvJUIrVAYoZw8QCSxOLSlKLIKKGRjDhkPLUnLJUiI5ipdhYAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"1, 3 or 12 months" = _t, Name = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"1, 3 or 12 months", Int64.Type}, {"Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

